default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
development:
  adapter: mysql2
  database: bssas_db
  encoding: utf8
  username: root
  password: password
  host: localhost
production:
    adapter: mysql2
    database: bssas
    encoding: utf8
    username: root
    password: Wbinfo@25#

#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool:  5
#  username: postgres
#  password: postgres

#development:
#  <<: *default
#  database: bssas_test_development

#test:
#  <<: *default
#  database: bssas_test

#production:
#  <<: *default
#  database: bssas_test_development

